[matchmaker]
	tier = "basic-1d2"

[matchmaker.regions]
	lnd-atl = {}
	lnd-fra = {}

# Runtime configuration for the lobby's Docker container.
[matchmaker.docker]
	dockerfile = "Dockerfile"
	ports.default = { port = 5001 }
	
	[matchmaker.docker.env]
		PORT = "5001"

[matchmaker.game_modes]
	classic = { max_players = 50 }
	aliens = { max_players = 30 }

[cdn]
	build_command = "yarn run build:prod"
	build_output = "public/"

