[cdn]

[matchmaker]
	tier = "basic-1d2"
	idle_lobbies = { min = 0, max = 0 }

	[matchmaker.docker]
		[matchmaker.docker.env]
			PORT = '80'
			IS_PROD = '1'

		[matchmaker.docker.ports]
			default = { proto = "https", target = 80 }

	[matchmaker.game_modes.classic]
		max_players = 50

		[matchmaker.game_modes.classic.docker]

	[matchmaker.game_modes.aliens]
		max_players = 30

		[matchmaker.game_modes.aliens.docker]


[kv]

[identity]
	custom_display_names = [
		"Astronaut",
		"Cosmonaut",
		"Starman",
		"Spaceman",
		"Rocketman",
		"Pilot",
		"Rocketeer",
	]

	custom_avatars = [
		"6e934530-5578-433f-ad99-f9c4ae37a58d",
		"141acc40-3f92-46f2-a703-84d895ae156e",
		"de6ead0e-6f05-4da3-87f2-f45d48b054ee",
	]

