[cdn]

[matchmaker]
	[matchmaker.game_modes.default]
		tier = "basic-1d1"
		max_players = 16

		[matchmaker.game_modes.default.docker]
			args = []

			[matchmaker.game_modes.default.docker.env]
				PORT = "80"

			[matchmaker.game_modes.default.docker.ports]
				default = { proto = "https", target = 80 }

[kv]

