[cdn]

[matchmaker]
	[matchmaker.game_modes.default]
		tier = "basic-1d1"
		max_players = 50

		[matchmaker.game_modes.default.docker]
			args = []

			[matchmaker.game_modes.default.docker.env]
				PORT = '80'
				IS_PROD = '1'

			[matchmaker.game_modes.default.docker.ports]
				https = { proto = "https", target = 80 }

	[matchmaker.game_modes.aliens]
		tier = "basic-1d1"
		max_players = 30

		[matchmaker.game_modes.aliens.docker]
			args = []

			[matchmaker.game_modes.aliens.docker.env]
				PORT = '80'
				IS_PROD = '1'

			[matchmaker.game_modes.aliens.docker.ports]
				https = { proto = "https", target = 80 }

[kv]

